#!/bin/bash
##echo Welcome to MN auto-setup!
#echo Make sure you have transaction id [txid] of collateral transaction in your local core DWE application associated masternode.conf file
#echo Make sure you have masternodeprivkey generated and specified in local core DWE application associated masternode.conf file
e#cho During the installation you will need to enter your masternodeprivkey once. That will add it to VPS associated dwe.conf file
#[ "${USER:-}" = "root" ] || exec sudo "$0" "$@"
#if [ -n "`which apt-get`" ];
 #           then apt-get install -y watch nano screen git openssl ;
 #           elif [ -n "`which yum`" ];
  #          then yum -y install watch nano screen git openssl ;
#fi;
cd ~
git clone https://github.com/AndreV84/dwe
chmod +x dwe/dwe-cli dwe/dwed
mkdir ~/.dwe
echo PASTE the masternode private key, please. Then  press enter 
read masternodeprivkey 
echo $masternodeprivkey >sample
cat << EOF > ~/.dwe/dwe.conf 
rpcuser=$(openssl rand -hex 7)
rpcpassword=$(openssl rand -hex 22)
rpcallowip=127.0.0.1
externalip=$(wget -q -O- icanhazip.com)
server=1
daemon=1
logtimestamps=1
maxconnections=256
masternode=1
masternodeprivkey=$(cat sample)
EOF
cat ~/.dwe/dwe.conf
cd dwe
./dwed
watch exec ./dwe-cli getblockcount

